DisablePathCorrection: false
EnablePathEscape: false
FireMethodNotAllowed: true
DisableBodyConsumptionOnUnmarshal: true
DisableStartupLog: false
TimeFormat: Mon, 01 Jan 2006 15:04:05 GMT
Charset: UTF-8